# Generated by Django 6.0.5 on 2026-05-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
