# Generated by Django 6.0.5 on 2026-05-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0003_roadmaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delo_app.roadmaps')),
            ],
        ),
    ]
