# Generated by Django 6.0.5 on 2026-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0004_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stages',
            options={'ordering': ['Roadmap', 'id']},
        ),
        migrations.AddField(
            model_name='stages',
            name='Stagetitle',
            field=models.CharField(default='12.12.12', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadmaps',
            name='Title',
            field=models.CharField(max_length=35),
        ),
    ]
