# Generated by Django 6.0.5 on 2026-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0005_alter_stages_options_stages_stagetitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='goald_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='progres',
            field=models.IntegerField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='status',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
