# Generated by Django 6.0.5 on 2026-05-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0006_stages_goald_date_stages_progres_stages_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasktitle', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=35, null=True)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delo_app.stages')),
            ],
            options={
                'ordering': ['Stage', 'id'],
            },
        ),
    ]
