# Generated by Django 6.0.5 on 2026-05-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0007_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmaps',
            options={'ordering': ['User']},
        ),
        migrations.AlterField(
            model_name='roadmaps',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaps',
            name='goald_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Steptitle', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=35, null=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delo_app.tasks')),
            ],
            options={
                'ordering': ['Task', 'id'],
            },
        ),
    ]
