# Generated by Django 6.0.5 on 2026-05-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delo_app', '0008_alter_roadmaps_options_alter_roadmaps_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmaps',
            options={'ordering': ['User', '-id']},
        ),
        migrations.AddField(
            model_name='roadmaps',
            name='Badge',
            field=models.CharField(max_length=310, null=True),
        ),
    ]
